// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateResponse(ctx context.Context, arg CreateResponseParams) error
	CreateState(ctx context.Context, arg CreateStateParams) error
	GetState(ctx context.Context, userID int64) (State, error)
}

var _ Querier = (*Queries)(nil)
